/**
 * The bootstrap script `init` writes into a consumer repository.
 *
 * It fetches the pinned tool from its release and runs it, so a consumer needs no
 * checkout of this repository. The script is intentionally small and stable.
 */
export const SHIM = `#!/bin/sh
# Bootstrap and run the pinned coding-harness tool (generated by harness init).
set -e
manifest=harness.manifest.json
version=$(node -p "require('./$manifest').tool.version")
source=$(node -p "const m=require('./$manifest');(m.tool&&m.tool.source)||(m.base&&m.base.source)||''")
case "$source" in
  git:*)
    url=\${source#git:}
    dir=".harness/tool/v$version"
    if [ ! -d "$dir/.git" ]; then
      git clone --depth 1 --branch "v$version" --no-tags "$url" "$dir"
    fi
    tool="$dir/bin/harness.mjs"
    ;;
  *)
    tool="$(dirname "$source")/bin/harness.mjs"
    ;;
esac
exec node "$tool" "$@"`
