/**
 * The bootstrap script `init` writes into a consumer repository.
 *
 * It fetches the pinned tool from its release, verifies the fetched commit
 * against the manifest pin, and only then runs it.
 */
export const SHIM = `#!/bin/sh
# Bootstrap and run the pinned coding-harness tool (generated by harness init).
set -e
manifest=harness.manifest.json
version=$(node -p "require('./$manifest').tool.version")
commit=$(node -p "const m=require('./$manifest');(m.tool&&m.tool.commit)||''")
source=$(node -p "const m=require('./$manifest');(m.tool&&m.tool.source)||(m.base&&m.base.source)||''")
case "$source" in
  git:*)
    url=\${source#git:}
    dir=".harness/tool/v$version"
    if [ ! -d "$dir/.git" ]; then
      git clone --depth 1 --branch "v$version" --no-tags "$url" "$dir"
    fi
    if [ -n "$commit" ]; then
      actual=$(git -C "$dir" rev-parse HEAD)
      if [ "$actual" != "$commit" ]; then
        echo "harness: fetched tool $actual does not match pinned $commit" >&2
        exit 1
      fi
    fi
    tool="$dir/bin/harness.mjs"
    ;;
  *)
    tool="$(dirname "$source")/bin/harness.mjs"
    ;;
esac
exec node "$tool" "$@"`
